#:schema node_modules/wrangler/config-schema.json
name = "mta-sts-static"
compatibility_date = "2024-10-18"
assets = { directory = "./public" }
routes = [
  { pattern = "mta-sts.example1.com", custom_domain = true },
  { pattern = "mta-sts.example2.com", custom_domain = true }
]

# Workers Logs - DO NOT WORK FOR ASSETS ONLY DEPLOYMENTS
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
# [observability]
# enabled = true
